SELECT A AS ANIMAL_ID, C AS NAME FROM
(SELECT A.ANIMAL_ID AS A, B.ANIMAL_ID AS B, A.NAME AS C FROM ANIMAL_OUTS A, ANIMAL_INS B 
WHERE A.ANIMAL_ID = B.ANIMAL_ID (+)
) X
WHERE X.B IS NULL
ORDER BY ANIMAL_ID
