SELECT Z.D,Z.C FROM
    (
    SELECT * FROM 
    (
    SELECT A.ANIMAL_ID AS A, B.ANIMAL_ID AS B, A.DATETIME AS C, A.NAME AS D FROM ANIMAL_INS A, ANIMAL_OUTS B
    WHERE A.ANIMAL_ID = B.ANIMAL_ID (+) 
        ) X
        WHERE X.B IS NULL 
    ORDER BY X.C
        ) Z
    WHERE ROWNUM<=3
