SELECT A AS ANIMAL_ID, C AS NAME FROM 
    (
    SELECT A.ANIMAL_ID AS A , B.ANIMAL_ID AS B, A.NAME AS C,A.DATETIME AS D, B.DATETIME AS E 
        FROM ANIMAL_INS A, ANIMAL_OUTS B
        WHERE A.ANIMAL_ID = B.ANIMAL_ID
    ORDER BY (D - E)
    ) X
WHERE ROWNUM<=2
