SELECT HH, SUM(COUNT) AS COUNT FROM 
    (SELECT TO_NUMBER(LEVEL-1) AS HH, 0 AS COUNT FROM DUAL CONNECT BY LEVEL <=24
    UNION ALL
    SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HH, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS 
    GROUP BY TO_CHAR(DATETIME,'HH24')
     )
GROUP BY HH
ORDER BY HH
